### ISSUE TITLE
Sample rate for MCP3002 in power meter application?

### ISSUE THREAD

**Issue by JDat** [davecrump/portsdown4#84]
What is sample rate and/or CLKrate for MCP3002 in power meter application?

**Comment by Montilien** [comment]
Hi,
I installed Langstone-V2 on Pi4 running Lime SDR mini. When I launch Langstone, it return to me "Lang_TRX_Lime.py failed to load".
I checked if the file really exist in Langstone Folder, and it is OK.
Have you some idea about such issue?
73's
F1FHK

**Comment by davecrump** [comment]
Hi

Please check the Forum here [Langstone Discussion](https://forum.batc.org.uk/viewforum.php?f=129) and ask if you cannot find the answer.  I suspect that you do not have the correct microphone dongle connected.  This is a Langstone problem, not a Portsdown problem.  Dave, G8GKQ

**Comment by Montilien** [comment]
Thanks, it was the cause of the issue. I have changed USB audio adapter and all goes right!...
________________________________
De : Dave Crump ***@***.***>
Envoyé : mercredi 28 décembre 2022 12:25
À : davecrump/portsdown4 ***@***.***>
Cc : Montilien ***@***.***>; Comment ***@***.***>
Objet : Re: [davecrump/portsdown4] Sample rate for MCP3002 in power meter application? (#84)


Hi

Please check the Forum here Langstone Discussion<https://forum.batc.org.uk/viewforum.php?f=129> and ask if you cannot find the answer. I suspect that you do not have the correct microphone dongle connected. This is a Langstone problem, not a Portsdown problem. Dave, G8GKQ
